"""US1 end-to-end — catalog mounts reviews; single-hop nested fetch.

Validates SC-001 (correct nested results) and SC-003 (one gql query per
mounted service per traversal, regardless of N parents → no network-level
N+1). Uses httpx ASGITransport to call the reviews ASGI app in-process.
"""

from __future__ import annotations

import httpx
import pytest
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlmodel import Field, SQLModel
from sqlmodel.ext.asyncio.session import AsyncSession
from starlette.applications import Starlette
from starlette.routing import Mount

from nexusx import GraphQLHandler
from nexusx.federation import RemoteRelationship
from nexusx.federation.http import GraphQLTransport
from nexusx.federation.introspect import build_federable_app
from nexusx.standard_queries import AutoQueryConfig

# Entity classes are defined INSIDE the fixture with unique tablenames so each
# test gets fresh classes → freshly generated by_* methods bound to THAT test's
# session_factory. (Module-global classes would retain stale methods from the
# first test's session_factory across tests — add_standard_queries mutates the
# class, which is correct in production but breaks per-test engine rotation.)

_fed_counter = 0


class CountingTransport(GraphQLTransport):
    def __init__(self, client):
        super().__init__(client=client)
        self.gql_calls = 0

    async def post_json(self, url, body):
        if "/graphql" in url:
            self.gql_calls += 1
        return await super().post_json(url, body)


def _new_engine():
    # File-based temp DB: robust across event loops (in-memory + StaticPool is
    # flaky when pytest-asyncio rotates loops between tests in one process).
    import os
    import tempfile

    fd, path = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    engine = create_async_engine(f"sqlite+aiosqlite:///{path}")
    return engine, path


async def _seed(engine, session_factory, rows):
    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)
    async with session_factory() as session:
        for r in rows:
            session.add(r)
        await session.commit()


@pytest.fixture
async def federation():
    global _fed_counter
    _fed_counter += 1
    n = _fed_counter

    class CatalogBase(SQLModel):
        pass

    class ReviewsBase(SQLModel):
        pass

    class Product(CatalogBase, table=True):
        __tablename__ = f"fed_e2e_product_{n}"
        id: int | None = Field(default=None, primary_key=True)
        name: str
        __relationships__ = [
            RemoteRelationship(
                name="reviews", target="reviews.Review",
                join_local="id", join_remote="product_id", is_list=True,
            ),
        ]

    class Review(ReviewsBase, table=True):
        __tablename__ = f"fed_e2e_review_{n}"
        id: int | None = Field(default=None, primary_key=True)
        product_id: int
        title: str
        rating: int

    # Reviews service DB + handler + ASGI app.
    rev_engine, rev_path = _new_engine()
    rev_sf = async_sessionmaker(rev_engine, class_=AsyncSession, expire_on_commit=False)
    await _seed(rev_engine, rev_sf, [
        Review(id=1, product_id=1, title="R1", rating=5),
        Review(id=2, product_id=1, title="R2", rating=3),
        Review(id=3, product_id=2, title="R3", rating=4),
        Review(id=4, product_id=3, title="R4", rating=2),
    ])
    reviews_handler = GraphQLHandler(
        base=ReviewsBase, session_factory=rev_sf,
        auto_query_config=AutoQueryConfig(batch_keys={"Review": ["product_id"]}),
        service_name="reviews",
    )
    reviews_app = build_federable_app(reviews_handler)

    # Catalog service DB + handler.
    cat_engine, cat_path = _new_engine()
    cat_sf = async_sessionmaker(cat_engine, class_=AsyncSession, expire_on_commit=False)
    await _seed(cat_engine, cat_sf, [
        Product(id=1, name="P1"), Product(id=2, name="P2"), Product(id=3, name="P3"),
    ])
    catalog_handler = GraphQLHandler(
        base=CatalogBase, session_factory=cat_sf,
        auto_query_config=AutoQueryConfig(), service_name="catalog",
    )

    # Composite ASGI app: reviews mounted at /reviews.
    composite = Starlette(routes=[Mount("/reviews", app=reviews_app)])
    client = httpx.AsyncClient(
        transport=httpx.ASGITransport(app=composite), base_url="http://test",
    )
    transport = CountingTransport(client=client)

    await catalog_handler.federate({"reviews": "http://test/reviews"}, transport=transport)

    yield catalog_handler, transport

    await client.aclose()
    await rev_engine.dispose()
    await cat_engine.dispose()
    import os
    for p in (rev_path, cat_path):
        try:
            os.unlink(p)
        except OSError:
            pass


@pytest.mark.asyncio
async def test_single_hop_nested_results_correct(federation):
    catalog_handler, transport = federation
    res = await catalog_handler.execute(
        "{ Product { by_filter { id name reviews { title rating } } } }"
    )
    assert not res.get("errors"), res
    products = res["data"]["Product"]["by_filter"]
    by_id = {p["id"]: p for p in products}
    assert sorted(r["title"] for r in by_id[1]["reviews"]) == ["R1", "R2"]
    assert [r["title"] for r in by_id[2]["reviews"]] == ["R3"]
    assert [r["title"] for r in by_id[3]["reviews"]] == ["R4"]
    # rating passthrough
    assert by_id[1]["reviews"][0]["rating"] in (5, 3)


@pytest.mark.asyncio
async def test_one_gql_query_per_mounted_service(federation):
    """SC-003: N parents (3 products) → reviews receives exactly ONE gql query."""
    catalog_handler, transport = federation
    assert transport.gql_calls == 0  # federate() only did a GET (introspection)
    await catalog_handler.execute(
        "{ Product { by_filter { id reviews { title } } } }"
    )
    assert transport.gql_calls == 1


@pytest.mark.asyncio
async def test_no_overfetch_when_remote_field_unselected(federation):
    catalog_handler, transport = federation
    await catalog_handler.execute("{ Product { by_filter { id name } } }")
    assert transport.gql_calls == 0  # reviews never contacted


@pytest.mark.asyncio
async def test_single_by_id_also_one_query(federation):
    catalog_handler, transport = federation
    await catalog_handler.execute("{ Product { by_id(id: 1) { id reviews { title } } } }")
    assert transport.gql_calls == 1
