"""Federation end-to-end (US1 single-hop + US2 multi-hop β nested forwarding).

Uses httpx ASGITransport to call the reviews ASGI app in-process. Entities + a
single engine per service are defined at MODULE level (mirroring conftest) so
SQLModel's global class-registry sees each class exactly once (no per-fixture
name collisions) and the auto-generated by_* methods bind once to stable
session factories.

- SC-001 / SC-003: single-hop — N parents → exactly one gql query to reviews.
- SC-002: multi-hop — product.reviews.author; author resolved inside the
  reviews fetch (β coalescing), catalog sends one gql to reviews.
"""

# NO `from __future__ import annotations` — SQLModel relationship forward-refs
# (list["FedReview"], Optional["FedUser"]) must resolve as real ForwardRefs.

import os
import tempfile
from typing import Optional

import httpx
import pytest
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlmodel import Field, Relationship, SQLModel
from sqlmodel.ext.asyncio.session import AsyncSession
from starlette.applications import Starlette
from starlette.routing import Mount

from nexusx import GraphQLHandler
from nexusx.federation import RemoteRelationship, RemoteService
from nexusx.federation.http import GraphQLTransport
from nexusx.federation.introspect import build_federable_app
from nexusx.standard_queries import AutoQueryConfig

# Remote service root — name + url, referenced by FedProduct below.
reviews = RemoteService("reviews", url="http://test/reviews")

# ── Module-level entities (single registration) ─────────────────────────

class CatalogBase(SQLModel):
    pass


class ReviewsBase(SQLModel):
    pass


class FedUser(ReviewsBase, table=True):
    __tablename__ = "fed_e2e_user"
    id: int | None = Field(default=None, primary_key=True)
    name: str
    reviews_authored: list["FedReview"] = Relationship(back_populates="author")


class FedReview(ReviewsBase, table=True):
    __tablename__ = "fed_e2e_review"
    id: int | None = Field(default=None, primary_key=True)
    product_id: int
    title: str
    rating: int
    author_id: int = Field(foreign_key="fed_e2e_user.id")
    author: Optional["FedUser"] = Relationship(back_populates="reviews_authored")


class FedProduct(CatalogBase, table=True):
    __tablename__ = "fed_e2e_product"
    id: int | None = Field(default=None, primary_key=True)
    name: str
    __relationships__ = [
        RemoteRelationship(
            name="reviews", target=reviews.FedReview,
            join_local="id", join_remote="product_id", is_list=True,
        ),
    ]


# ── Module-level engines (one per service, singleton) ────────────────────

def _file_engine():
    fd, path = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    return create_async_engine(f"sqlite+aiosqlite:///{path}"), path


_cat_engine, _cat_path = _file_engine()
_rev_engine, _rev_path = _file_engine()
_cat_sf = async_sessionmaker(_cat_engine, class_=AsyncSession, expire_on_commit=False)
_rev_sf = async_sessionmaker(_rev_engine, class_=AsyncSession, expire_on_commit=False)

_seeded = False


async def _ensure_seed():
    global _seeded
    if _seeded:
        return
    async with _cat_engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)
    async with _rev_engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)
    async with _cat_sf() as s:
        for p in (
            FedProduct(id=1, name="P1"),
            FedProduct(id=2, name="P2"),
            FedProduct(id=3, name="P3"),
        ):
            s.add(p)
        await s.commit()
    async with _rev_sf() as s:
        s.add(FedUser(id=1, name="Alice"))
        s.add(FedUser(id=2, name="Bob"))
        s.add(FedReview(id=1, product_id=1, title="R1", rating=5, author_id=1))
        s.add(FedReview(id=2, product_id=1, title="R2", rating=3, author_id=2))
        s.add(FedReview(id=3, product_id=2, title="R3", rating=4, author_id=1))
        s.add(FedReview(id=4, product_id=3, title="R4", rating=2, author_id=2))
        await s.commit()
    _seeded = True


class CountingTransport(GraphQLTransport):
    def __init__(self, client):
        super().__init__(client=client)
        self.gql_calls = 0

    async def post_json(self, url, body):
        if "/graphql" in url:
            self.gql_calls += 1
        return await super().post_json(url, body)


async def _build_catalog_and_transport():
    """Fresh catalog handler (its own ErManager) + a counting transport.

    by_* methods on the module-level classes are generated once (first handler)
    and bind to the module-level session factories; subsequent handlers reuse
    them safely. Each catalog handler's ErManager is independent and gets its
    own federated relationships via federate().
    """
    await _ensure_seed()
    reviews_handler = GraphQLHandler(
        base=ReviewsBase, session_factory=_rev_sf,
        auto_query_config=AutoQueryConfig(batch_keys={"FedReview": ["product_id"]}),
        service_name="reviews",
    )
    reviews_app = build_federable_app(reviews_handler)

    catalog_handler = GraphQLHandler(
        base=CatalogBase, session_factory=_cat_sf,
        auto_query_config=AutoQueryConfig(), service_name="catalog",
    )
    composite = Starlette(routes=[Mount("/reviews", app=reviews_app)])
    client = httpx.AsyncClient(
        transport=httpx.ASGITransport(app=composite), base_url="http://test",
    )
    transport = CountingTransport(client=client)
    await catalog_handler.er.initialize(transport=transport)
    return catalog_handler, transport, client


@pytest.fixture
async def federation():
    catalog_handler, transport, client = await _build_catalog_and_transport()
    yield catalog_handler, transport
    await client.aclose()


# ── US1: single-hop ─────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_single_hop_nested_results_correct(federation):
    catalog_handler, transport = federation
    res = await catalog_handler.execute(
        "{ FedProduct { by_filter { id name reviews { title rating } } } }"
    )
    assert not res.get("errors"), res
    products = res["data"]["FedProduct"]["by_filter"]
    by_id = {p["id"]: p for p in products}
    assert sorted(r["title"] for r in by_id[1]["reviews"]) == ["R1", "R2"]
    assert [r["title"] for r in by_id[2]["reviews"]] == ["R3"]
    assert [r["title"] for r in by_id[3]["reviews"]] == ["R4"]


@pytest.mark.asyncio
async def test_one_gql_query_per_mounted_service(federation):
    """SC-003: N parents (3 products) → reviews receives exactly ONE gql query."""
    catalog_handler, transport = federation
    assert transport.gql_calls == 0  # federate() only did a GET (introspection)
    await catalog_handler.execute("{ FedProduct { by_filter { id reviews { title } } } }")
    assert transport.gql_calls == 1


@pytest.mark.asyncio
async def test_no_overfetch_when_remote_field_unselected(federation):
    catalog_handler, transport = federation
    await catalog_handler.execute("{ FedProduct { by_filter { id name } } }")
    assert transport.gql_calls == 0


@pytest.mark.asyncio
async def test_single_by_id_also_one_query(federation):
    catalog_handler, transport = federation
    await catalog_handler.execute("{ FedProduct { by_id(id: 1) { id reviews { title } } } }")
    assert transport.gql_calls == 1


# ── US2: multi-hop (β nested forwarding) ────────────────────────────────

@pytest.mark.asyncio
async def test_multihop_nested_author_resolved_by_reviews(federation):
    """SC-002: product.reviews.author — author resolved inside the reviews fetch."""
    catalog_handler, transport = federation
    res = await catalog_handler.execute(
        "{ FedProduct { by_id(id: 1) { id reviews { title author { name } } } } }"
    )
    assert not res.get("errors"), res
    reviews = res["data"]["FedProduct"]["by_id"]["reviews"]
    by_title = {r["title"]: r for r in reviews}
    assert by_title["R1"]["author"]["name"] == "Alice"
    assert by_title["R2"]["author"]["name"] == "Bob"
    assert "reviews." not in str(res)  # no service prefix


@pytest.mark.asyncio
async def test_multihop_one_gql_query_to_reviews(federation):
    """catalog sends exactly ONE gql query to reviews (author resolved internally)."""
    catalog_handler, transport = federation
    await catalog_handler.execute(
        "{ FedProduct { by_id(id: 1) { reviews { title author { name } } } } }"
    )
    assert transport.gql_calls == 1
