"""ER fragment wire types — the federation introspection payload.

Serialized by the member-side ER introspection endpoint and consumed by the
mounter's ``FederatedTypeRegistry``. Mirrors ``RelationshipInfo`` field
semantics; loader callables are deliberately NOT serialized (they are code,
not data). This is the federation composition source — same source as
Voyager/executor, not GraphQL SDL.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class FieldDescriptor(BaseModel):
    """A scalar field on an entity."""

    name: str
    type_name: str


class RelDescriptor(BaseModel):
    """One relationship on an entity (local or remote)."""

    name: str
    direction: str
    fk_field: str
    target_typename: str
    is_list: bool = False
    sort_field: str | None = None
    # Remote relationships carry the owning service + endpoint so the mounter
    # can discover the reachable subgraph transitively (FR-005).
    target_service: str | None = None
    target_endpoint: str | None = None


class EntityFragment(BaseModel):
    """One entity type as exposed by a member's ER introspection."""

    typename: str
    scalar_fields: list[FieldDescriptor] = Field(default_factory=list)
    relationships: list[RelDescriptor] = Field(default_factory=list)
    # Names of generated by_<key>_in batch query roots on this type.
    batch_roots: list[str] = Field(default_factory=list)


class ERIntrospectionResponse(BaseModel):
    """Full ER introspection payload for one member service."""

    service_name: str
    entities: list[EntityFragment] = Field(default_factory=list)
